name: "build resource pack"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Optimize resource pack"
    runs-on: "ubuntu-latest"

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare pack with short commit SHA
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "Using short commit SHA: $SHORT_SHA"

          cp -r pack temp-pack
          FILE="temp-pack/pack.mcmeta"

          perl -pi -e "s/<COMMIT-SHA>/$SHORT_SHA/g" "$FILE"

          echo "Updated $FILE content:"
          cat "$FILE"

      - name: Run PackSquash on temp-pack
        uses: ComunidadAylas/PackSquash-action@v4.0.3
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'temp-pack'
            zip_spec_conformance_level = 'high'
            output_file_path = '/tmp/pack.zip'

            ['**/*?.fsh']
            force_include = true
            ['**/*?.vsh']
            force_include = true

      - name: Tag and create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            /tmp/pack.zip
